/**
 * Тексты публичной страницы бронирования отеля на русском и английском.
 * Иностранцу, под которого сделана регистрационная карта EN/RU, нужна и
 * витрина на понятном языке (ревьюер). Названия и описания категорий, адрес и
 * правила приходят с сервера как есть — их перевод на стороне отеля.
 */
export type PublicHotelLang = "ru" | "en";

const ruNights = (n: number): string => (n % 10 === 1 && n % 100 !== 11 ? "ночь" : [2, 3, 4].includes(n % 10) && ![12, 13, 14].includes(n % 100) ? "ночи" : "ночей");

export const PUBLIC_HOTEL_TEXT = {
  ru: {
    locale: "ru-RU",
    currencyKgs: "сом",
    nights: (n: number) => `${n} ${ruNights(n)}`,
    nightsWord: ruNights,
    titleSuffix: "бронирование номера",
    fallbackTitle: "Бронирование номера",
    direct: "Бронирование напрямую в отеле",
    chooseDates: "Выберите даты и номер",
    times: (inTime: string, outTime: string) => `Заезд с ${inTime} · выезд до ${outTime}`,
    unavailable: "Бронирование через сайт для этого отеля сейчас недоступно. Свяжитесь с отелем по телефону.",
    accepted: "Заявка принята",
    reference: "Номер брони",
    heldUntil: (time: string) => `Номер зарезервирован до ${time}`,
    acceptedText: (sum: string, phone: string) =>
      `Сумма — ${sum}. Администратор отеля подтвердит бронь и свяжется с вами по телефону ${phone}. Если подтверждения не будет до конца резерва, номер вернётся в продажу.`,
    checkIn: "Заезд",
    checkOut: "Выезд",
    adults: "Взрослых",
    children: "Детей",
    searching: "Ищем…",
    search: "Найти номера",
    noRooms: (guests: number) => `На эти даты свободных номеров для ${guests} ${guests === 1 ? "гостя" : "гостей"} нет. Попробуйте другие даты.`,
    periodLine: (from: string, to: string, nights: string) => `Заезд ${from} — выезд ${to} · ${nights} · цена за весь период`,
    capacity: (guests: number, left: number) => `до ${guests} гостей · осталось ${left}`,
    more: (n: number) => `ещё ${n}`,
    perNight: (sum: string) => `≈ ${sum} за ночь`,
    chosen: "Выбрано",
    choose: "Выбрать",
    yourDetails: "Ваши данные",
    holdNote: "Номер зарезервируется на 30 минут, пока администратор подтвердит бронь.",
    cancellation: "Отмена:",
    cancellationUnknown: "условия отмены администратор назовёт при подтверждении брони.",
    payment: "Оплата:",
    paymentText: "на сайте ничего платить не нужно — способ и срок оплаты подтвердит администратор.",
    fullName: "Имя и фамилия",
    phone: "Телефон",
    email: "Эл. почта",
    optional: "Необязательно",
    wishes: "Пожелания",
    wishesPlaceholder: "Поздний заезд, детская кроватка…",
    consent: "Согласен(на) на обработку персональных данных для бронирования",
    consentRequired: "Без согласия заявку отправить нельзя",
    sending: "Отправляем…",
    send: "Отправить заявку",
    nextPhoto: (name: string) => `Следующее фото «${name}»`,
    photo: (name: string) => `Фото «${name}»`,
    // Ошибки
    pickDates: "Выберите даты",
    pastCheckIn: "Заезд не может быть в прошлом",
    checkOutAfter: "Выезд должен быть позже заезда",
    maxNights: (n: number) => `Не больше ${n} ночей`,
    tooFar: "Бронирование открыто не дальше чем на два года",
    rateLimited: "Слишком много запросов. Подождите минуту и повторите.",
    siteOff: "Бронирование через сайт для этого отеля недоступно.",
    searchFailed: "Не удалось получить свободные номера",
    priceChanged: (sum: string) => `Цена изменилась: теперь ${sum}. Проверьте и нажмите «Отправить заявку» ещё раз.`,
    categoryGone: "Эта категория больше недоступна на выбранные даты. Выберите другую.",
    priceChangedReload: "Цена изменилась. Обновите страницу и повторите.",
    noAvailability: "Свободных номеров этой категории на выбранные даты больше нет. Выберите другую категорию или даты.",
    retry: "Заявку не удалось отправить. Нажмите «Отправить заявку» ещё раз.",
    sendFailed: "Не удалось отправить заявку. Попробуйте ещё раз.",
    nameError: null as string | null,
    phoneError: null as string | null,
    emailError: null as string | null,
    board: {} as Record<string, string>,
  },
  en: {
    locale: "en-GB",
    currencyKgs: "KGS",
    nights: (n: number) => `${n} ${n === 1 ? "night" : "nights"}`,
    nightsWord: (n: number): string => (n === 1 ? "night" : "nights"),
    titleSuffix: "book a room",
    fallbackTitle: "Book a room",
    direct: "Book directly with the hotel",
    chooseDates: "Choose dates and a room",
    times: (inTime: string, outTime: string) => `Check-in from ${inTime} · check-out until ${outTime}`,
    unavailable: "Online booking for this hotel is not available right now. Please call the hotel.",
    accepted: "Request received",
    reference: "Booking reference",
    heldUntil: (time: string) => `The room is held until ${time}`,
    acceptedText: (sum: string, phone: string) =>
      `Total — ${sum}. The hotel will confirm the booking and call you at ${phone}. If it is not confirmed before the hold ends, the room goes back on sale.`,
    checkIn: "Check-in",
    checkOut: "Check-out",
    adults: "Adults",
    children: "Children",
    searching: "Searching…",
    search: "Find rooms",
    noRooms: (guests: number) => `No rooms are free for ${guests} ${guests === 1 ? "guest" : "guests"} on these dates. Try other dates.`,
    periodLine: (from: string, to: string, nights: string) => `Check-in ${from} — check-out ${to} · ${nights} · price for the whole stay`,
    capacity: (guests: number, left: number) => `up to ${guests} guests · ${left} left`,
    more: (n: number) => `${n} more`,
    perNight: (sum: string) => `≈ ${sum} per night`,
    chosen: "Selected",
    choose: "Select",
    yourDetails: "Your details",
    holdNote: "The room is held for 30 minutes while the hotel confirms your booking.",
    cancellation: "Cancellation:",
    cancellationUnknown: "the hotel will tell you the cancellation terms when it confirms the booking.",
    payment: "Payment:",
    paymentText: "nothing to pay on the website — the hotel will confirm how and when to pay.",
    fullName: "Full name",
    phone: "Phone",
    email: "Email",
    optional: "Optional",
    wishes: "Requests",
    wishesPlaceholder: "Late arrival, baby cot…",
    consent: "I agree to the processing of my personal data for this booking",
    consentRequired: "We cannot send the request without your consent",
    sending: "Sending…",
    send: "Send request",
    nextPhoto: (name: string) => `Next photo of “${name}”`,
    photo: (name: string) => `Photo of “${name}”`,
    pickDates: "Choose dates",
    pastCheckIn: "Check-in cannot be in the past",
    checkOutAfter: "Check-out must be after check-in",
    maxNights: (n: number) => `No more than ${n} nights`,
    tooFar: "Bookings are open up to two years ahead",
    rateLimited: "Too many requests. Wait a minute and try again.",
    siteOff: "Online booking is not available for this hotel.",
    searchFailed: "Could not load free rooms",
    priceChanged: (sum: string) => `The price has changed: it is now ${sum}. Check it and press “Send request” again.`,
    categoryGone: "This room type is no longer available for these dates. Choose another one.",
    priceChangedReload: "The price has changed. Reload the page and try again.",
    noAvailability: "No rooms of this type are left for these dates. Choose another room type or dates.",
    retry: "The request was not sent. Press “Send request” again.",
    sendFailed: "Could not send the request. Please try again.",
    // Ошибки полей формы: на английском — свои короткие тексты вместо русских правил формы.
    nameError: "Enter your name" as string | null,
    phoneError: "Enter a Kyrgyzstan phone number" as string | null,
    emailError: "Check the email address" as string | null,
    board: {
      none: "Room only",
      breakfast: "Breakfast",
      half_board: "Half board",
      full_board: "Full board",
      all_inclusive: "All inclusive",
    } as Record<string, string>,
  },
} satisfies Record<PublicHotelLang, unknown>;

export type PublicHotelText = (typeof PUBLIC_HOTEL_TEXT)["ru"];

/** ?lang=en в ссылке, иначе язык браузера (не русский и не кыргызский — английский). */
export function initialPublicHotelLang(search: string, browserLang: string | undefined): PublicHotelLang {
  const fromUrl = new URLSearchParams(search).get("lang");
  if (fromUrl === "en" || fromUrl === "ru") return fromUrl;
  const lang = (browserLang ?? "ru").toLowerCase();
  return lang.startsWith("ru") || lang.startsWith("ky") ? "ru" : "en";
}
